name: v2g
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  fpdart: ^1.1.1
  go_router: ^15.0.0
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.8
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  retrofit_generator: ^9.1.9
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  riverpod_generator: ^2.6.5
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true